### ISSUE TITLE
StockCurve[A].item returns a collection of items

### ISSUE THREAD

**Issue by stewSquared** [andreaferretti/paths-js#23]
So, according to the [documentation](https://github.com/andreaferretti/paths-js/wiki/Stock-charts), `Stock.curves` returns a collection of curves, "each having the properties `line`, `area`, `item` and `index`. [...] Under item one finds the original element in the data."

The problem is that this implies that each curve is associated with a singular item, despite the fact that the curve is dependent on a series of items. This is formalized in the explicitly typed scala.js [documentation](http://andreaferretti.github.io/paths-scala-js/index.html#paths.high.StockCurve). Where the type of `StockCurve[A].item` is `A` rather than `Array[A]`

This is inspite of the fact the `.item` actually returns an array, leading to a runtime error when treating item like an A.

**Comment by andreaferretti** [comment]
Thank you, I have fixed the documentation and accepted your PR on paths-scala-js

**Comment by stewSquared** [comment]
Thanks! I'm loving this library, by the way. The level of control I have over the final output is great, yet my code remains small and clean.
