### ISSUE TITLE
Sector not able to wrap around 0. 

### ISSUE THREAD

**Issue by tnrich** [andreaferretti/paths-js#30]
Hey there, I'm trying to draw a Sector (represented by the blue highlight here) with 
```
startAngle: 2.2244817547157543
endAngle: 1.6781178149610074
```
in a clockwise direction. Unfortunately this is what I'm ending up with currently when passing in those angles to the command: 

![image](https://cloud.githubusercontent.com/assets/2730609/10877402/c710850e-80fa-11e5-9ba0-c23d95b90571.png)

Ideally the blue highlight would loop around the whole circle, but it seems like I can't draw a sector that passes through the 0-angle right now? 

Is there a way to achieve this? If not, maybe a clockwise flag could be added to allow for it? 

Desired output:
![image](https://cloud.githubusercontent.com/assets/2730609/10877487/7ccd9ba2-80fb-11e5-98c1-0d5113ded1ca.png)

Thank you

**Comment by andreaferretti** [comment]
Sorry it took a while to have a look at this, maybe it is not useful anymore. But it is pretty easy: if you want to wrap around 0, just put a value of `end` greater than 2 * pi. I just tested this works as expected
