### ISSUE TITLE
Bezier curves error out on minus method

### ISSUE THREAD

**Issue by ekosz** [andreaferretti/paths-js#31]
Hi there I'm using paths-js version 0.3.5 and I'm having issues with Bezier curves. Anytime I try to generate a curve either though a `SmothCurve` graph or directly using the `Bezier` function, I get an error.  Here is a way to reproduce the error.

```node
> var Bezier = require('paths-js/bezier');
undefined
> Bezier({points: [[97,219],[119.69932031054931,198.5]]})
TypeError: Cannot read property '0' of undefined
    at Object.module.exports.minus (node_modules/paths-js/ops.js:38:13)
    at module.exports.reflect (node_modules/paths-js/bezier.js:14:14)
    at node_modules/paths-js/bezier.js:27:41
> Bezier({points: [[0,0],[1,1]]})
TypeError: Cannot read property '0' of undefined
  [snip]
```

As you can see, even the simple example going from (0,0) to (1,1) errors out. Is there something I'm doing wrong here?

**Comment by andreaferretti** [comment]
You are right, Bezier curves only work for three or more points. They should not give an error - on two points it would make sense to just draw the line between the points - so it was a mistake on my part.

I am correcting this error, but right now I am in the mid of a translation. Many people are leaving coffeescript for ES6 and I do not want to leave paths.js on a dead end, hence I am rewriting it into ES6. I am almost done, so I should have a new release by the end of the week or so. After that, I will fix the issue.

In the meantime, you can check that you are using at least three points, and when you get less, use a line.

**Comment by andreaferretti** [comment]
I have fixed the issue on the version that is coming in a few days. I could quickly fix it on the coffeescript version as well, but then making a release takes a little time

**Comment by andreaferretti** [comment]
Should be fixed now in version `0.4.0-beta`

**Comment by ekosz** [comment]
@andreaferretti Awesome, should I close this issue? 

Sorry for bothering you with this, I figured the multiple points out a couple hours after opening this issue and reading the source code for a bit.

**Comment by andreaferretti** [comment]
Sure, just check it works for you before closing! ;-)
