### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by inkxe-karma** [andreaferretti/paths-js#38]
![capture2](https://cloud.githubusercontent.com/assets/13641705/13904009/e31b2436-ee4e-11e5-8c56-0dace6562f49.PNG)

**Comment by inkxe-karma** [comment]
is showing error         ReferenceError: require is not defined

**Comment by andreaferretti** [comment]
What version of Paths are you using? The one in a single file, that for AMD, the one for Common.js... ?

Also, I am not sure what the linked image has to do with issue
