### ISSUE TITLE
Ability to max-width rectangles?

### ISSUE THREAD

**Issue by ojame** [andreaferretti/paths-js#43]
Heya. Firstly, rad library, I'm really enjoying it. Is there an easy way to supply a max-width for individual columns in the waterfall and bar charts? My problem is if I have only 2 data points for a waterfall, but the graph is the width of 1200px, those columns are really wide. I could reduce the size of the graph - but it's a dynamic graph that could have over 20 columns.

For example, it currently might look like this:

![chart1](https://cloud.githubusercontent.com/assets/2898239/18768568/89711d42-8169-11e6-9f10-ec2f6fed718e.png)

If i could supply it a max column width, to look like this:

![chart2](https://cloud.githubusercontent.com/assets/2898239/18768570/953aadd2-8169-11e6-98c1-50ebcba01e86.png)

Any ideas? Thanks!

**Comment by andreaferretti** [comment]
Unfortunately, there is no such option yet. I might add it, but I am a bit afraid of making the API too complex. What you can do for now is just precompute on your own the expected width of data and use it as width - note that this bears not relation to the actual SVG size, which you can keep as big as you need to accomodate larger graphs.

All in all the change would amount to just adding a line after [here](https://github.com/andreaferretti/paths-js/blob/master/src/bar.js#L25) to cap the width and adding a test, so if you really think it is worth I could easily add it as an option
