### ISSUE TITLE
Specify a starting point for Bar charts

### ISSUE THREAD

**Issue by jwerre** [andreaferretti/paths-js#45]
What would be the best way to offset the bar chart before printing it?

```
var offset = 100;

var chart = Bar({
	data: [...],
	width: 400,
	height: 400,
	// --> offset: [100, 100]
});

chart.curves.forEach( function(curve, index) {
	console.log( curve.line.path.print() )
});

// The log outputs something like this
// M 46 84...
// M 93 56...

// but what I need is the offset (100) added to M:
// M 146 184...
// M 193 156...

```

I used `center` for Pie charts which seemed to work fine but I'm not sure how this would be done with Bar.

**Comment by andreaferretti** [comment]
You can just put the bar chart in a <g> tag with a transform= translate
attribute (see the examples in the demo).

I am trying to keep the Api minimal and avoid doing things that can be done
in svg itself.

Il giorno gio 15 dic 2016 alle 02:08 Jonah Werre <notifications@github.com>
ha scritto:

**Comment by jwerre** [comment]
I'm printing to PDFKit so I actually do need the SVG path.

**Comment by andreaferretti** [comment]
I see. I will add an offset parameter, then

**Comment by andreaferretti** [comment]
Added the option `offset: [20, 50]` in version 0.4.5
