### ISSUE TITLE
Stock can't be used to draw step chart

### ISSUE THREAD

**Issue by UrKr** [andreaferretti/paths-js#46]
The stock graph function is written in a way which prevents the drawing of a step chart. 

![image](https://cloud.githubusercontent.com/assets/7669179/21440956/fd7686d2-c895-11e6-9908-4619e4a646fd.png)

I've been fiddling with drawing a step chart for the better part of the evening, and I finally found why it wouldn't render correctly. 

In src/line-chart-comp.js on line 8
`
  let sorted = points.sort(([a, b], [c, d]) => a - c)
`
This sorts the data by x (presumably so that if unsorted data gets passed in, it renders as expected). If I want to draw a step chart, I'm going to have to add in multiple points with the same x, which might change index after an unstable sort. As a result, the points of a step in the step chart would be connected out of order.

For example, these are the points the library generates.
1. [0, 200] 
2. [34.1747572815534, 200]
3. [34.1747572815534, 0]
4. [43.49514563106796, 200]
5. [43.49514563106796, 0]

4. and 5. were swapped by the unstable sort. In my original data they were in the reversed position. If you chart these points you wouldn't get a step chart, but if you swapped 4.  and 5., you would.

I suppose removing the sort at this point would be a breaking change, but how about adding an option?

**Comment by andreaferretti** [comment]
Added the option `sort: false` in version 0.4.5

**Comment by UrKr** [comment]
That was fast, thanks!
