### ISSUE TITLE
Pie-chart with only one slice

### ISSUE THREAD

**Issue by msageryd** [andreaferretti/paths-js#47]
path-js works great, most of the time, for me. But when I end up with data for only one slice (i.e. 100% of the data), the slice is not drawn.

If I set a stroke color I can see that only the line from center to perimeter (radius) is drawn. Is there any properties I have forgot to set? Otherwise it seems like some kind of bug where a full circle (360 degrees) become a null circle (0 degrees).

**Comment by andreaferretti** [comment]
Sorry it took a while :-)

**Comment by msageryd** [comment]
A year is nothing =)
Great, now I can remove my workaround!
