### ISSUE TITLE
Move to Babel 7

### ISSUE THREAD

**Issue by mfirry** [andreaferretti/paths-js#48]
Babel changed quite a bit from 5 to 6 (`babel-cli`, [transform-plugins-modules](https://babeljs.io/docs/plugins/#transform-plugins-modules), just to mention a few of the changes).

We should probably find the time to upgrade the build and possibly remove browserify.

**Comment by andreaferretti** [comment]
PR? ;-)

**Comment by mfirry** [comment]
Wow. Time flies. Babel is now at 7.9.0. I'll see if I find the time to upgrade a little.
