### ISSUE TITLE
Path: transformations for vline and hline commands fail

### ISSUE THREAD

**Issue by rkalapuc** [andreaferretti/paths-js#55]
Steps to reproduce:
```
var path = Path()
  .moveto(10, 20)
  .vlineto(30, 50)
  .hlineto(25, 28)
  .qcurveto(27, 30, 32, 27)
  .translate(10, 10)
  .closepath();
```

Exception:
```
      x: point.x * matrix[0] + point.y * matrix[2] + matrix[4],
                         ^

TypeError: Cannot read property '0' of undefined
    at C:\dev\sandbox\paths-js\dist\node\geom.js:73:26
```

**Comment by andreaferretti** [comment]
`vlineto` and `hlineto` take a single coordinate as input, since the other one is fixed. So you example should read

```js
var path = Path()
  .moveto(10, 20)
  .vlineto(30)
  .hlineto(25)
  .qcurveto(27, 30, 32, 27)
  .translate(10, 10)
  .closepath();
```

**Comment by rkalapuc** [comment]
Thanks for a reply. 

Nevertheless it will fail anyway if you try to apply transformation. The root cause is [here](https://github.com/andreaferretti/paths-js/blob/490afdd226de2f727c55f4bd4217ef2b91065026/src/path.js#L83) and [here](https://github.com/andreaferretti/paths-js/blob/490afdd226de2f727c55f4bd4217ef2b91065026/src/path.js#L68) - `matrix` is not passed to `matrixTransform`

**Comment by andreaferretti** [comment]
Good catch! There was also another mistake in that function, now it should be fine. Going to release 0.4.8
