### ISSUE TITLE
Error while using paths-js as a yarn/npm dependency

### ISSUE THREAD

**Issue by dwongfaull** [andreaferretti/paths-js#57]
We're currently using a library that depends on paths-js and transpiling to ES5 (don't ask) using Babel and webpack. This gives an error in npm reporting "Module not found, can't resolve paths-js." This is because webpack expects the default entry to be index.js, but the entry to paths-js is all.js.

This can be solved by adding a line to the package.json `"main": "./all.js"`. I'm unsure if this will break a more typical use case, but I can't see why it would.

**Comment by andreaferretti** [comment]
Sure. I will be out for a few days, so if you open a PR, I can integrate it when I come back.

**Comment by HarunOr** [comment]
Hey, I just noticed that the npm package still has the old package.json without the main entry.
